config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resource :settings, only: [:show, :update]
  end

  root to: "search#index"
  post "/", controller: :search, action: :index

  resources :libraries do
    resources :models, except: [:index, :destroy] do
      member do
        post "merge"
      end
      collection do
        get "edit", action: "bulk_edit"
        patch "update", action: "bulk_update"
      end
      resources :model_files, except: [:index, :destroy] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :creators
end

app/models/model_file.rb
class ModelFile < ApplicationRecord
  belongs_to :model
  validates :filename, presence: true, uniqueness: {scope: :model}

  default_scope { order(:filename) }

  def file_format
    File.extname(filename).delete(".").downcase
  end

  def name
    File.basename(filename, ".*").humanize.titleize
  end

  def pathname
    File.join(model.library.path, model.path, filename)
  end

  def calculate_digest
    Digest::SHA512.new.file(pathname).hexdigest
  rescue Errno::ENOENT
    nil
  end
end

app/controllers/model_files_controller.rb
class ModelFilesController < ApplicationController
  before_action :get_library
  before_action :get_model
  before_action :get_file, except: [:bulk_edit, :bulk_update]

  def show
    respond_to do |format|
      format.html
      format.js
      format.stl { send_file_content }
      format.obj { send_file_content }
      format.threemf { send_file_content }
      format.ply { send_file_content }
      format.blend { send_file_content }
      format.mix { send_file_content }
      format.png { send_file File.join(@library.path, @model.path, @file.filename) }
      format.jpeg { send_file File.join(@library.path, @model.path, @file.filename) }
      format.svg { send_file File.join(@library.path, @model.path, @file.filename) }
      format.gif { send_file File.join(@library.path, @model.path, @file.filename) }
    end
  end

  def update
    @file.update(file_params)
    redirect_to [@library, @model, @file]
  end

  def bulk_edit
    @files = @model.model_files
  end

  def bulk_update
    hash = bulk_update_params
    params[:model_files].each_pair do |id, selected|
      if selected == "1"
        file = @model.model_files.find(id)
        if file.update(hash)
          file.save
        end
      end
    end
    redirect_to edit_library_model_model_files_path(@library, @model)
  end

  private

  def send_file_content
    filename = File.join(@library.path, @model.path, @file.filename)
    response.headers["Content-Length"] = File.size(filename).to_s
    send_file filename, disposition: :inline, type: @file.file_format.to_sym
  rescue Errno::ENOENT
    head :internal_server_error
  end

  def bulk_update_params
    params.permit(
      :printed,
      :presupported,
      :y_up
    ).compact_blank
  end

  def file_params
    params.require(:model_file).permit([
      :printed,
      :presupported,
      :y_up
    ])
  end

  def get_library
    @library = Library.find(params[:library_id])
  end

  def get_model
    @model = @library.models.find(params[:model_id])
  end

  def get_file
    @file = @model.model_files.find(params[:id])
    @title = @file.name
  end
end

app/helpers/model_files_helper.rb
module ModelFilesHelper
end

app/views/model_files/_form.html.erb
<%= form_with model: [@library, @model, @file] do |form| %>
  <div class="form-check form-switch mb-3">
    <%= form.check_box :printed, class: 'form-check-input' %>
    <label class="form-check-label" for="printed">Printed?</label>
  </div>
  <div class="form-check form-switch mb-3">
    <%= form.check_box :presupported, class: 'form-check-input' %>
    <label class="form-check-label" for="presupported">Presupported?</label>
  </div>
  <div class="form-check form-switch mb-3">
    <%= form.check_box :y_up, class: 'form-check-input' %>
    <label class="form-check-label" for="y_up">Y Up</label>
  </div>
  <%= form.submit "Update", class: 'btn btn-primary' %>
<% end %>

app/views/model_files/bulk_edit.html.erb
<h1>Bulk Edit Files</h1>

<%= form_with url: library_model_model_files_path(@library, @model), method: :patch do |form| %>

  <h3>Select files to change:</h3>

  <table class="table table-striped" data-bulk-edit>
    <tr>
      <th><input type="checkbox" aria-label="Select All" value="0" name="bulk-select-all"></th>
      <th></th>
      <th>Name</th>
      <th>Filename</th>
      <th>Printed</th>
      <th>Presupported</th>
      <th>Y Up</th>
    </tr>
    <% @model.model_files.each do |file| %>
      <tr>
        <td><%= form.check_box "model_files[#{file.id}]", { data: { bulk_item:  "#{file.id}"}}%></td>
        <td><i class="bi bi-<%= image?(file.file_format) ? 'image' : 'box' %>"></td>
        <td><%= link_to file.name, [@library, @model, file], title: file.filename %></td>
        <td><code><%= file.filename %></code></td>
        <td><i class="bi bi-<%= file.printed ? 'check-circle-fill' : 'circle' %>"></td>
        <td><i class="bi bi-<%= file.presupported ? 'check-circle-fill' : 'circle' %>"></td>
        <td><i class="bi bi-<%= file.y_up ? 'check-circle-fill' : 'circle' %>"></td>
      </tr>
    <% end %>
  </table>

  <h3>Select changes to make:</h3>

  <div class="row mb-3">
    <%= form.label "Printed", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-switch">
        <%= form.check_box :printed, class: "form-check-input form-check-inline" %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label "Presupported", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-switch">
        <%= form.check_box :presupported, class: "form-check-input form-check-inline" %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label "Y Up", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-switch">
        <%= form.check_box :y_up, class: "form-check-input form-check-inline" %>
      </div>
    </div>
  </div>
  <%= form.submit "Update Selected Files", class: "btn btn-primary" %>

<% end %>

app/views/model_files/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to @model.name, [@library, @model] %></li>
  </ol>
</nav>
<h1><%= @file.name %></h1>

<div class="row row-cols-2">

  <div class="col-9">
      <% if image?(@file.file_format) %>
        <%= image_tag library_model_model_file_path(@model.library, @model, @file, format: @file.file_format), alt: @file.name, style: "width: 100%" %>
      <% elsif renderable?(@file.file_format) %>
        <%= render partial: "object_preview", locals: { library: @library, model: @model, file: @file } %>
      <% end %>
  </div>

  <div class="col-3">
    <%= card :secondary, "Details" do %>
      <p>
        Filename: <code><%= @file.filename %></code>
      </p>
      <% if @file.digest %>
        <p>
          Digest: <code><%= @file.digest.slice(0,16) %></code>
        </p>
      <% end %>
      <%= render 'form' %>
    <% end %>

    <%= card :secondary, "Actions" do %>
      <%= link_to "#{icon('cloud-download', 'Download')} Download".html_safe, library_model_model_file_path(@library, @model, @file, @file.file_format.to_sym), {class: "btn btn-secondary"} %>
    <% end %>

  </div>
</div>