config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resource :settings, only: [:show, :update]
  end

  root to: "search#index"
  post "/", controller: :search, action: :index

  resources :libraries do
    resources :models, except: [:index, :destroy] do
      member do
        post "merge"
      end
      collection do
        get "edit", action: "bulk_edit"
        patch "update", action: "bulk_update"
      end
      resources :model_files, except: [:index, :destroy] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :creators
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(:name) }
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :models, dependent: :destroy
  has_many :model_files, through: :models
  validates :path, presence: true, uniqueness: true, existing_path: true

  default_scope { order(:path) }

  def name
    File.basename(path)
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  def host
    URI.parse(url).host
  end

  def site
    PublicSuffix.parse(host).sld.to_sym
  end
end

app/models/model.rb
class Model < ApplicationRecord
  extend Memoist

  belongs_to :library
  belongs_to :creator, optional: true
  has_many :model_files, dependent: :destroy
  belongs_to :preview_file, class_name: "ModelFile", optional: true
  validates :name, presence: true
  validates :path, presence: true, uniqueness: {scope: :library}
  has_many :links, as: :linkable, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  attr_accessor :organize

  before_update :move_files

  default_scope { order(:name) }
  scope :recent, -> { unscoped.order(created_at: :desc) }

  acts_as_taggable_on :tags

  def autogenerate_tags_from_path!
    tags = File.split(path).last.split(/[\W_+-]/).filter { |x| x.length > 1 }

    if SiteSettings.model_tags_filter_stop_words
      @filter ||= Stopwords::Snowball::Filter.new(SiteSettings.model_tags_stop_words_locale, SiteSettings.model_tags_custom_stop_words)
      tags = @filter.filter(tags)
    end

    unless tags.empty?
      tag_list.add(tags)
      save!
    end
  end

  def parents
    Pathname.new(path).parent.descend.map do |path|
      library.models.find_by_path(path.to_s)
    end.compact
  end
  memoize :parents

  def merge_into!(target)
    return unless target

    # Work out path to this model from the target
    relative_path = Pathname.new(path).relative_path_from(Pathname.new(target.path))
    # Move files
    model_files.each do |f|
      f.update(
        filename: File.join(relative_path, f.filename),
        model: target
      )
    end
    reload
    destroy
  end

  def formatted_path
    File.join("", tags.order(taggings_count: :desc).map(&:to_s).map(&:parameterize), name.parameterize) + "##{id}"
  end

  def contained_models
    library.models.where("path LIKE ?", Model.sanitize_sql_like(path) + "/%")
  end

  def contains_other_models?
    contained_models.exists?
  end

  private

  def create_folder_if_necessary(folder)
    return if Dir.exist?(folder)
    create_folder_if_necessary(File.dirname(folder))
    Dir.mkdir(folder)
  end

  def move_files
    if ActiveModel::Type::Boolean.new.cast(organize) && !contains_other_models?
      old_path = File.join(library.path, path)
      new_path = File.join(library.path, formatted_path)
      create_folder_if_necessary(File.dirname(new_path))
      File.rename(old_path, new_path)
      self.path = formatted_path
    end
  end
end

app/models/model_file.rb
class ModelFile < ApplicationRecord
  belongs_to :model
  validates :filename, presence: true, uniqueness: {scope: :model}

  default_scope { order(:filename) }

  def file_format
    File.extname(filename).delete(".").downcase
  end

  def name
    File.basename(filename, ".*").humanize.titleize
  end

  def pathname
    File.join(model.library.path, model.path, filename)
  end

  def calculate_digest
    Digest::SHA512.new.file(pathname).hexdigest
  rescue Errno::ENOENT
    nil
  end
end

app/models/site_settings.rb
# RailsSettings Model
class SiteSettings < RailsSettings::Base
  cache_prefix { "v1" }

  field :model_tags_filter_stop_words, type: :boolean, default: true
  field :model_tags_stop_words_locale, type: :string, default: "en"
  field :model_tags_custom_stop_words, type: :array, default: Rails.configuration.formats.flatten(2).select { |x| x.is_a?(String) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable

  def to_param
    username
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :get_library
  before_action :get_model, except: [:bulk_edit, :bulk_update]

  def show
    @groups = helpers.group(@model.model_files)
  end

  def edit
    @creators = Creator.all
    @model.links.build if @model.links.empty? # populate empty link
  end

  def update_tags(tags)
    old_tags = Set.new(@model.tag_list)
    new_tags = Set.new(tags.reject(&:blank?))

    intersect = old_tags & new_tags
    additions = new_tags.subtract(intersect)
    @model.tag_list = intersect + additions
    @model.save
  end

  def update
    hash = model_params
    tags = hash.delete(:tags)

    if @model.update(hash)
      update_tags(tags.split(",")) if tags
    end

    redirect_to [@library, @model]
  end

  def merge
    if (target = (@model.parents.find { |x| x.id == params[:target].to_i }))
      @model.merge_into! target
      redirect_to [@library, target]
    else
      render status: :bad_request
    end
  end

  def bulk_edit
    @creators = Creator.all
    @models = @library.models
    if (@tag = params[:tag])
      @models = @models.tagged_with(@tag)
    end
  end

  def bulk_update
    hash = bulk_update_params

    add_tags = (hash.delete(:add_tags) { |t| "" }).split(",").reject(&:blank?)
    remove_tags = (hash.delete(:remove_tags) { |t| "" }).split(",").reject(&:blank?)

    add_tags = Set.new(add_tags)
    remove_tags = Set.new(remove_tags)

    params[:models].each_pair do |id, selected|
      if selected == "1"
        model = @library.models.find(id)
        if model.update(hash)
          existing_tags = Set.new(model.tag_list)
          model.tag_list = existing_tags + add_tags - remove_tags
          model.save
        end
      end
    end
    redirect_to edit_library_models_path(@library, tag: params[:tag])
  end

  private

  def bulk_update_params
    params.permit(
      :scale_factor,
      :creator_id,
      :add_tags,
      :remove_tags,
      :organize
    ).compact_blank
  end

  def model_params
    params.require(:model).permit(
      :preview_file_id,
      :creator_id,
      :name,
      :scale_factor,
      :tags,
      :organize,
      links_attributes: [:id, :url, :_destroy]
    )
  end

  def get_library
    @library = Library.find(params[:library_id])
  end

  def get_model
    @model = @library.models.includes(:model_files, :creator).find(params[:id])
    @title = @model.name
  end
end

app/helpers/models_helper.rb
module ModelsHelper
  def group(files)
    groups = files.group_by { |i| i.filename.split(/[\ _\-:.]/)[0] }
    ungrouped = []
    groups.each_pair do |group, p|
      ungrouped << groups.delete(group)[0] if p.count == 1
    end
    groups.merge(nil => ungrouped)
  end
end

app/views/models/_file.html.erb
<div class="col mb-4">
  <div class="card <%= file === @model.preview_file ? "border-primary" : "" %>"%>
    <% if image?(file.file_format) %>
      <%= image_tag library_model_model_file_path(@library, @model, file, format: file.file_format), class: "card-img-top image-preview", alt: file.name %>
    <% elsif renderable?(file.file_format) %>
      <div class="card-img-top">
        <%= render partial: "object_preview", locals: { library: @library, model: @model, file: file } %>
      </div>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= file.name %></h5>
      <%= form_with model: [@library, @model] do |form| %>
        <%= link_to "Details", library_model_model_file_path(@library, @model, file), {class: "btn btn-primary"} %>
        <%= link_to icon('cloud-download', 'Download'), library_model_model_file_path(@library, @model, file, file.file_format.to_sym), {class: "btn btn-secondary"} %>
        <%= form.hidden_field :preview_file_id, value: file.id %>
        <%= form.button icon('bookmark-heart', 'Set as preview'), class: "btn btn-secondary #{file == @model.preview_file ? "disabled" : ""}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/models/_form.html.erb
<%= form_with model: [@library, @model] do |form| %>
  <form>
    <div class="row mb-3 input-group">
      <%= form.label :name, class: "col-sm-2 col-form-label" %>
      <%= form.text_field :name, class: "form-control col-auto" %>
    </div>

    <div class="row mb-3 input-group">
      <%= form.label :scale_factor, class: "col-sm-2 col-form-label" %>
      <%= form.number_field :scale_factor, class: "form-control col-auto" %>
    </div>

    <div class="row mb-3 input-group">
      <%= form.label :preview_file, class: "col-sm-2 col-form-label" %>
      <div class='col-sm-10 ps-0'>
        <%= form.collection_select :preview_file_id, @model.model_files, :id, :name, {}, {class: "form-control form-select"} %>
        <span id="previewFileHelp" class="form-text">The file displayed as a model preview in library pages</span>
      </div>
    </div>

    <div class="row mb-3 input-group">
      <%= form.label :creator_id, class: "col-sm-2 col-form-label" %>
      <%= form.collection_select :creator_id, @creators, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
      <%= link_to "New Creator", new_creator_path, class: "btn btn-outline-secondary col-auto" %>
    </div>

    <%= render 'tags_edit', :form => form, :name => "model[tags]", :value => (@model.tags.map { |tag| tag.name }).join(","), :label => "Tags" %>

    <%= render 'links_form', :form => form %>

    <%= form.submit "Save", class: "btn btn-primary" %>
  </form>
<% end %>

app/views/models/_tags_edit.html.erb
<div class="row mb-3">
  <label for="tags" class="col-sm-2 col-form-label"><%= label %></label>
  <div class="col-sm-10">
    <div class="form-control col-auto tag-container">
      <%= form.text_field :tags,
        as: :string,
        name: name,
        value: value,
        data: { tags_edit: "" }
      %>
    </div>
  </div>
</div>

app/views/models/bulk_edit.html.erb
<h1>Bulk Edit Models</h1>
<% if @tag %>
  <p class="lead">Tagged with &quot;<%= @tag %>&quot;</p>
<% end %>

<%= form_with url: library_models_path(@library), method: :patch do |form| %>

  <h3>Select models to change:</h3>

  <table class="table table-striped" data-bulk-edit>
    <tr>
      <th><input type="checkbox" aria-label="Select All" value="0" name="bulk-select-all"></th>
      <th>Name</th>
      <th>Scale Factor</th>
      <th>Tags</th>
      <th>Creator</th>
      <th>Organize files</th>
    </tr>
    <% @models.each do |model| %>
      <tr>
        <td><%= form.check_box "models[#{model.id}]", { data: { bulk_item:  "#{model.id}"}}%></td>
        <td><%= link_to model.name, [@library, model], title: model.path %></td>
        <td><%= number_to_percentage model.scale_factor, strip_insignificant_zeros: true %></td>
        <td><%= render partial: 'tag', collection: model.tags.sort_by(&:taggings_count), locals: {selected: nil, model_id: model.id } %></td>
        <td><%= link_to model.creator.name, model.creator if model.creator %></td>
        <td><code><%= model.formatted_path if model.formatted_path != model.path %></code></td>
      </tr>
    <% end %>
  </table>

  <h3>Select changes to make:</h3>

  <div class="row mb-3">
    <%= form.label :scale_factor, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.number_field :scale_factor, class: "form-control col-auto" %>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :creator_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.collection_select :creator_id, @creators, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
        <%= link_to "New Creator", new_creator_path, class: "btn btn-outline-secondary col-auto" %>
      </div>
    </div>
  </div>

  <%= render 'tags_edit', :form => form, :name => :add_tags, :value => "", :label => "Add Tags" %>
  <%= render 'tags_edit', :form => form, :name => :remove_tags, :value => "", :label => "Remove Tags" %>

  <div class="row mb-3">
    <%= form.label "Organize files", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-switch">
        <%= form.check_box :organize, class: "form-check-input form-check-inline" %>
      </div>
    </div>
  </div>

  <%= form.hidden_field :tag, value: @tag if @tag %>
  <%= form.submit "Update Selected Models", class: "btn btn-primary" %>

<% end %>

app/views/models/edit.html.erb
<h1>Edit Model</h1>

<%= render 'form' %>

app/views/models/show.html.erb
<h1><%= @model.name %></h1>
<div class="row row-cols-2">

  <div class="col-9">
    <h2><a name="files">Files</a></h2>
    <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
      <%= render partial: "file", collection: @groups.delete(nil) %>
    </div>
    <% @groups.each_pair do |group, files| %>
      <h3><a name="<%= group.parameterize %>"><%= group %></a></h3>
      <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
        <%= render partial: "file", collection: files %>
      </div>
    <% end %>
  </div>

  <div class="col-3">

    <%= card :secondary, "Details" do %>
      <% if @model.creator %>
        <p>
          Creator: <%= link_to @model.creator.name, creator_path(@model.creator) %>
        </p>
      <% end %>
      <p>
        Path: <code><%= @model.path %></code>
      </p>
      <p>
        Scale: <%= number_to_percentage @model.scale_factor, strip_insignificant_zeros: true %>
      </p>
    <% end %>

    <%= card :secondary, "Actions" do %>
      <%= link_to "Edit Details", edit_library_model_path(@library, @model), class: "btn btn-primary" %>
      <%= link_to "Bulk Edit", edit_library_model_model_files_path(@library, @model), class: 'btn btn-secondary' %>
      <% unless @model.contains_other_models? %>
        <div class="modal fade" id="confirm-move" data-bs-backdrop='static' tabindex="-1" aria-labelledby="confirmMoveLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="confirmMoveLabel">Organize files</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>
                  The folder and files that make up this model will be moved from:<br>
                  <code><%= @model.path %></code><br>
                  to<br>
                  <code><%= @model.formatted_path %></code>
                </p>
                <p>
                  Are you sure you want to do this?
                </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No, cancel</button>
                <%= button_to "Yes, move the files", library_model_path(@library, @model, "model[organize]": true), method: :patch, class: "btn btn-warning" %>
              </div>
            </div>
          </div>
        </div>
        <%= button_tag "Organize Files", class: "btn btn-warning", "data-bs-toggle": "modal", "data-bs-target": "#confirm-move" %>
      <% end %>
    <% end %>

    <%= card :secondary, "Sections" do %>
      <a href="#files">Files</a>
      <ul>
        <% @groups.each_pair do |group, files| %>
          <li><a href="#<%= group.parameterize %>"><%= group %></a></li>
        <% end %>
      </ul>
    <% end %>

    <%= render 'tags_card', tags: @model.tags.sort_by(&:taggings_count), selected: nil %>
    <%= render 'links_card', links: @model.links %>

    <% if @model.contains_other_models? %>
      <%= card :warning, "Contained Models" do %>
        <p>
          The model folder on disk contains other models. You may wish to merge them into this one, or move them out.
        </p>
        <ul>
          <% @model.contained_models.each do |target| %>
            <li><%= link_to target.name, library_model_path(@library, target)%></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>

    <% unless @model.parents.empty? %>
      <%= card :danger, "Merge" do %>
        <p>
          Merging moves all files from this model to the target, and removes this model. File metadata is preserved, but any model metadata will be lost!
        </p>
        <strong>Merge with:</strong>
        <% @model.parents.each do |target| %>
          <%= link_to target.name, merge_library_model_path(@library, @model, target: target.id), class: "btn btn-danger", method: :post %>
        <% end %>
      <% end %>
    <% end %>

  </div>

</div>