config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resource :settings, only: [:show, :update]
  end

  root to: "search#index"
  post "/", controller: :search, action: :index

  resources :libraries do
    resources :models, except: [:index, :destroy] do
      member do
        post "merge"
      end
      collection do
        get "edit", action: "bulk_edit"
        patch "update", action: "bulk_update"
      end
      resources :model_files, except: [:index, :destroy] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :creators
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(:name) }
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :get_creator, except: [:index, :new, :create]

  def index
    @creators =
      if current_user.pagination_settings["creators"]
        page = params[:page] || 1
        Creator.all.page(page).per(current_user.pagination_settings["per_page"])
      else
        Creator.all
      end
    @title = "Creators"
  end

  def show
    @models = @creator.models
  end

  def edit
    @creator.links.build if @creator.links.empty? # populate empty link
  end

  def update
    @creator.update(creator_params)
    redirect_to @creator
  end

  def new
    @creator = Creator.new
    @creator.links.build if @creator.links.empty? # populate empty link
    @title = "New Creator"
  end

  def create
    @creator = Creator.create(creator_params)
    redirect_to @creator
  end

  def destroy
    @creator.destroy
    redirect_to creators_path
  end

  private

  def get_creator
    @creator = Creator.find(params[:id])
    @title = @creator.name
  end

  def creator_params
    params.require(:creator).permit([
      :name,
      links_attributes: [:id, :url, :_destroy]
    ])
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/_creator.html.erb
<div class="col mb-4">
  <div class="card"%>
    <div class="card-body">
      <h5 class="card-title"><%= creator.name %></h5>
      <p class="card-text"><%= pluralize creator.models.count, "models" %></p>
      <%= link_to "Details", creator, {class: "btn btn-primary"} %>
    </div>
  </div>
</div>

app/views/creators/_form.html.erb
<%= form_with model: @creator do |form| %>
  <form>
    <div class="row mb-3 input-group">
      <%= form.label :name, class: "col-sm-2 col-form-label" %>
      <%= form.text_field :name, class: "form-control col-auto" %>
    </div>

    <%= render 'links_form', :form => form %>

    <%= form.submit "Save", class: "btn btn-primary" %>
  </form>
<% end %>

app/views/creators/edit.html.erb
<h1>Edit Creator</h1>

<%= render 'form' %>

app/views/creators/index.html.erb
<h1>Creators</h1>

<div class="row row-cols-2">
  <div class="col-9">
    <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-3 mb-3">
        <%= render @creators %>
    </div>
    <% if current_user.pagination_settings["creators"] %>
      <div class="paginate-container">
        <%= paginate @creators %>
      </div>
    <% end %>
  </div>
  <div class="col-3">

    <%= card :secondary, "Actions" do %>
      <%= link_to "New Creator", new_creator_path, class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/creators/new.html.erb
<h1>New Creator</h1>

<%= render 'form' %>

app/views/creators/show.html.erb
<h1><%= @creator.name %></h1>

<div class="row row-cols-2">
  <div class="col-9">

    <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
      <%= render partial: 'model', collection: @models %>
      <% if @models.empty? %>
        <div>No models yet!</div>
      <% end %>
    </div>

  </div>
  <div class="col-3">

    <%= render 'links_card', links: @creator.links %>

    <%= card(:secondary, 'Actions') do %>
      <%= link_to "Edit Details", edit_creator_path(@creator), class: "btn btn-primary" %>
      <%= link_to 'Delete', @creator, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    <% end %>

  </div>
</div>