config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resource :settings, only: [:show, :update]
  end

  root to: "search#index"
  post "/", controller: :search, action: :index

  resources :libraries do
    resources :models, except: [:index, :destroy] do
      member do
        post "merge"
      end
      collection do
        get "edit", action: "bulk_edit"
        patch "update", action: "bulk_update"
      end
      resources :model_files, except: [:index, :destroy] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :creators
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanDAM<%= " : #{@title}" if @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <%= javascript_include_tag "application" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.6/js/standalone/selectize.min.js" integrity="sha512-pgmLgtHvorzxpKra2mmibwH/RDAVMlOuqU98ZjnyZrOZxgAR8hwL8A02hQFWEK25V40/9yPYb/Zc+kyWMplgaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <%= stylesheet_link_tag "application" %>
</head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "#{icon("search", "Search")} Search".html_safe, root_path, class: (current_page?(root_path) ? "nav-link active" : "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to "#{icon('person-rolodex', 'Creators')} Creators".html_safe, creators_path, class: (current_page?(creators_path) ? "nav-link active" : "nav-link") %>
        </li>
        <% Library.all.each do |library| %>
          <li class="nav-item">
            <%= link_to library.name, library, class: (current_page?(library) ? "nav-link active" : "nav-link") %>
          </li>
        <% end %>
        <li class="nav-item me-auto">
          <%= link_to icon("folder-plus", "New Library"), new_library_path, class: (current_page?(new_library_path) ? "nav-link active" : "nav-link") %>
        </li>
        <% if @library&.persisted? || @scan_in_progress %>
          <li class="nav-item">
            <%= link_to (@scan_in_progress ? "<span class=\"spinner-border spinner-border-sm\" aria-hidden=\"true\"></span> Scanning".html_safe : "Rescan"),
              @library ? library_path(@library) : "",
              method: :patch,
              class: "btn btn-warning btn-sm mt-1 #{"btn-outline-warning disabled" if @scan_in_progress}"
            %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to icon('sliders', 'Settings'), user_settings_path(current_user), class: (current_page?(user_settings_path(current_user)) ? "nav-link active" : "nav-link") %>
        </li>
      </ul>

      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
      <footer class='mt-5 py-2 border-top'>
        VanDAM is Open Source, available from <%= link_to "GitHub", "https://github.com/Floppy/van_dam" %>.
        This server is cataloguing a total of <%= "#{Model.count} model".pluralize(Model.count) %>,
        with <%= "#{ModelFile.count} file".pluralize(ModelFile.count) %>,
        in <%= "#{Library.count} library".pluralize(Library.count) %>.
        <% if ENV.has_key? "VAN_DAM_GIT_REF" %>
          <span id='version'>
            <%= ENV.fetch "VAN_DAM_GIT_REF", "?" %>
            (<%= ENV.fetch "VAN_DAM_GIT_SHA", "?" %>)
          </span>
        <% end %>
      </footer>
    </div>
  </body>
</html>